#!/bin/bash

set -e

find ./vendor/cmark/cmark/src -type f -iregex ".*\.c" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/src -type f -iregex ".*\.h" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/src -type f -iregex ".*\.inc" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/src -type f -iregex ".*\.re" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/extensions -type f -iregex ".*\.c" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/extensions -type f -iregex ".*\.h" | xargs -I{} cp {} vendor/cmark
find ./vendor/cmark/cmark/extensions -type f -iregex ".*\.inc" | xargs -I{} cp {} vendor/cmark
sed '/#define HAVE___BUILTIN_EXPECT/d' vendor/cmark/config.h > vendor/cmark/config.h.new
mv vendor/cmark/config.h.new vendor/cmark/config.h
